import os
import shutil
import random
from pathlib import Path

# === CONFIGURATION ===
SOURCE_IMAGE_DIR = "images"
SOURCE_LABEL_DIR = "labels"
SOURCE_XML_DIR = "xml_labels"

OUTPUT_DIR = "dataset"
TRAIN_RATIO = 0.8  # 80%
VAL_RATIO = 0.1    # 10%
TEST_RATIO = 0.1   # 10%

RANDOM_SEED = 42  # For reproducibility

def create_directory_structure(output_dir):
    """Create train/val/test directory structure"""
    splits = ['train', 'val', 'test']
    subdirs = ['images', 'labels', 'xml_labels']
    
    for split in splits:
        for subdir in subdirs:
            path = os.path.join(output_dir, split, subdir)
            os.makedirs(path, exist_ok=True)
            print(f"Created: {path}")

def get_image_files(image_dir):
    """Get all image files from directory"""
    valid_extensions = {'.png', '.jpg', '.jpeg'}
    image_files = []
    
    for file in os.listdir(image_dir):
        if Path(file).suffix.lower() in valid_extensions:
            image_files.append(file)
    
    return sorted(image_files)

def split_dataset(image_files, train_ratio, val_ratio, test_ratio, seed=42):
    """Split files into train/val/test sets"""
    random.seed(seed)
    
    # Shuffle the files
    shuffled_files = image_files.copy()
    random.shuffle(shuffled_files)
    
    total = len(shuffled_files)
    train_count = int(total * train_ratio)
    val_count = int(total * val_ratio)
    
    train_files = shuffled_files[:train_count]
    val_files = shuffled_files[train_count:train_count + val_count]
    test_files = shuffled_files[train_count + val_count:]
    
    return train_files, val_files, test_files

def copy_files(file_list, split_name, source_dirs, output_dir):
    """Copy images, labels, and XML files to respective split directories"""
    source_image_dir, source_label_dir, source_xml_dir = source_dirs
    
    copied_count = {
        'images': 0,
        'labels': 0,
        'xml_labels': 0
    }
    
    missing_files = {
        'labels': [],
        'xml_labels': []
    }
    
    for image_file in file_list:
        # Get base filename without extension
        base_name = Path(image_file).stem
        
        # Copy image
        src_image = os.path.join(source_image_dir, image_file)
        dst_image = os.path.join(output_dir, split_name, 'images', image_file)
        if os.path.exists(src_image):
            shutil.copy2(src_image, dst_image)
            copied_count['images'] += 1
        
        # Copy YOLO label
        label_file = f"{base_name}.txt"
        src_label = os.path.join(source_label_dir, label_file)
        dst_label = os.path.join(output_dir, split_name, 'labels', label_file)
        if os.path.exists(src_label):
            shutil.copy2(src_label, dst_label)
            copied_count['labels'] += 1
        else:
            missing_files['labels'].append(label_file)
        
        # Copy XML label
        xml_file = f"{base_name}.xml"
        src_xml = os.path.join(source_xml_dir, xml_file)
        dst_xml = os.path.join(output_dir, split_name, 'xml_labels', xml_file)
        if os.path.exists(src_xml):
            shutil.copy2(src_xml, dst_xml)
            copied_count['xml_labels'] += 1
        else:
            missing_files['xml_labels'].append(xml_file)
    
    return copied_count, missing_files

def create_yaml_file(output_dir, train_count, val_count, test_count):
    """Create YOLO dataset configuration file"""
    yaml_content = f"""# Khmer Text Detection Dataset
# Auto-generated by split_dataset.py

path: {os.path.abspath(output_dir)}  # dataset root dir
train: train/images  # train images (relative to 'path')
val: val/images      # val images (relative to 'path')
test: test/images    # test images (relative to 'path')

# Classes
names:
  0: word

# Dataset Statistics
train_samples: {train_count}
val_samples: {val_count}
test_samples: {test_count}
total_samples: {train_count + val_count + test_count}

# Split Ratios
train_ratio: {TRAIN_RATIO}
val_ratio: {VAL_RATIO}
test_ratio: {TEST_RATIO}
"""
    
    yaml_path = os.path.join(output_dir, 'data.yaml')
    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)
    
    print(f"\nCreated YOLO config: {yaml_path}")

def create_summary_file(output_dir, stats):
    """Create a summary file with dataset statistics"""
    summary_path = os.path.join(output_dir, 'dataset_summary.txt')
    
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write("=" * 70 + "\n")
        f.write("DATASET SPLIT SUMMARY\n")
        f.write("=" * 70 + "\n\n")
        
        f.write(f"Total Images: {stats['total']}\n\n")
        
        f.write(f"Train Set ({TRAIN_RATIO*100:.0f}%):\n")
        f.write(f"  Images: {stats['train']['images']}\n")
        f.write(f"  Labels: {stats['train']['labels']}\n")
        f.write(f"  XML Files: {stats['train']['xml_labels']}\n\n")
        
        f.write(f"Validation Set ({VAL_RATIO*100:.0f}%):\n")
        f.write(f"  Images: {stats['val']['images']}\n")
        f.write(f"  Labels: {stats['val']['labels']}\n")
        f.write(f"  XML Files: {stats['val']['xml_labels']}\n\n")
        
        f.write(f"Test Set ({TEST_RATIO*100:.0f}%):\n")
        f.write(f"  Images: {stats['test']['images']}\n")
        f.write(f"  Labels: {stats['test']['labels']}\n")
        f.write(f"  XML Files: {stats['test']['xml_labels']}\n\n")
        
        if stats['missing']:
            f.write("=" * 70 + "\n")
            f.write("MISSING FILES WARNING\n")
            f.write("=" * 70 + "\n\n")
            
            for split in ['train', 'val', 'test']:
                if stats['missing'][split]['labels']:
                    f.write(f"\n{split.upper()} - Missing Labels ({len(stats['missing'][split]['labels'])}):\n")
                    for missing in stats['missing'][split]['labels'][:10]:
                        f.write(f"  - {missing}\n")
                    if len(stats['missing'][split]['labels']) > 10:
                        f.write(f"  ... and {len(stats['missing'][split]['labels']) - 10} more\n")
                
                if stats['missing'][split]['xml_labels']:
                    f.write(f"\n{split.upper()} - Missing XML Files ({len(stats['missing'][split]['xml_labels'])}):\n")
                    for missing in stats['missing'][split]['xml_labels'][:10]:
                        f.write(f"  - {missing}\n")
                    if len(stats['missing'][split]['xml_labels']) > 10:
                        f.write(f"  ... and {len(stats['missing'][split]['xml_labels']) - 10} more\n")
    
    print(f"Created summary: {summary_path}")

def main():
    """Main function to split dataset"""
    print("=" * 70)
    print("DATASET SPLITTER FOR TEXT DETECTION")
    print("=" * 70)
    
    # Check if source directories exist
    if not os.path.exists(SOURCE_IMAGE_DIR):
        print(f"Error: Source image directory '{SOURCE_IMAGE_DIR}' not found!")
        return
    
    if not os.path.exists(SOURCE_LABEL_DIR):
        print(f"Error: Source label directory '{SOURCE_LABEL_DIR}' not found!")
        return
    
    if not os.path.exists(SOURCE_XML_DIR):
        print(f"Error: Source XML directory '{SOURCE_XML_DIR}' not found!")
        return
    
    # Get all image files
    print(f"\n[1] Scanning source directory: {SOURCE_IMAGE_DIR}")
    image_files = get_image_files(SOURCE_IMAGE_DIR)
    total_images = len(image_files)
    
    if total_images == 0:
        print("Error: No image files found!")
        return
    
    print(f"Found {total_images} images")
    
    # Create directory structure
    print(f"\n[2] Creating directory structure in: {OUTPUT_DIR}")
    create_directory_structure(OUTPUT_DIR)
    
    # Split dataset
    print(f"\n[3] Splitting dataset ({TRAIN_RATIO*100:.0f}% train, {VAL_RATIO*100:.0f}% val, {TEST_RATIO*100:.0f}% test)")
    train_files, val_files, test_files = split_dataset(
        image_files, TRAIN_RATIO, VAL_RATIO, TEST_RATIO, RANDOM_SEED
    )
    
    print(f"  Train: {len(train_files)} images")
    print(f"  Val:   {len(val_files)} images")
    print(f"  Test:  {len(test_files)} images")
    
    # Copy files
    source_dirs = (SOURCE_IMAGE_DIR, SOURCE_LABEL_DIR, SOURCE_XML_DIR)
    
    print(f"\n[4] Copying files...")
    print("-" * 70)
    
    # Copy train files
    print("Copying TRAIN set...")
    train_copied, train_missing = copy_files(train_files, 'train', source_dirs, OUTPUT_DIR)
    print(f"  ✓ Images: {train_copied['images']}, Labels: {train_copied['labels']}, XML: {train_copied['xml_labels']}")
    
    # Copy val files
    print("Copying VAL set...")
    val_copied, val_missing = copy_files(val_files, 'val', source_dirs, OUTPUT_DIR)
    print(f"  ✓ Images: {val_copied['images']}, Labels: {val_copied['labels']}, XML: {val_copied['xml_labels']}")
    
    # Copy test files
    print("Copying TEST set...")
    test_copied, test_missing = copy_files(test_files, 'test', source_dirs, OUTPUT_DIR)
    print(f"  ✓ Images: {test_copied['images']}, Labels: {test_copied['labels']}, XML: {test_copied['xml_labels']}")
    
    # Create statistics
    stats = {
        'total': total_images,
        'train': train_copied,
        'val': val_copied,
        'test': test_copied,
        'missing': {
            'train': train_missing,
            'val': val_missing,
            'test': test_missing
        }
    }
    
    # Create YAML config file for YOLO
    print(f"\n[5] Creating configuration files...")
    create_yaml_file(OUTPUT_DIR, len(train_files), len(val_files), len(test_files))
    
    # Create summary file
    create_summary_file(OUTPUT_DIR, stats)
    
    # Final summary
    print("\n" + "=" * 70)
    print("DATASET SPLIT COMPLETE!")
    print("=" * 70)
    print(f"\nDataset structure:")
    print(f"  {OUTPUT_DIR}/")
    print(f"  ├── train/")
    print(f"  │   ├── images/     ({train_copied['images']} files)")
    print(f"  │   ├── labels/     ({train_copied['labels']} files)")
    print(f"  │   └── xml_labels/ ({train_copied['xml_labels']} files)")
    print(f"  ├── val/")
    print(f"  │   ├── images/     ({val_copied['images']} files)")
    print(f"  │   ├── labels/     ({val_copied['labels']} files)")
    print(f"  │   └── xml_labels/ ({val_copied['xml_labels']} files)")
    print(f"  ├── test/")
    print(f"  │   ├── images/     ({test_copied['images']} files)")
    print(f"  │   ├── labels/     ({test_copied['labels']} files)")
    print(f"  │   └── xml_labels/ ({test_copied['xml_labels']} files)")
    print(f"  ├── data.yaml")
    print(f"  └── dataset_summary.txt")
    
    # Warnings
    total_missing_labels = len(train_missing['labels']) + len(val_missing['labels']) + len(test_missing['labels'])
    total_missing_xml = len(train_missing['xml_labels']) + len(val_missing['xml_labels']) + len(test_missing['xml_labels'])
    
    if total_missing_labels > 0 or total_missing_xml > 0:
        print("\nWARNINGS:")
        if total_missing_labels > 0:
            print(f"  - {total_missing_labels} missing label files")
        if total_missing_xml > 0:
            print(f"  - {total_missing_xml} missing XML files")
        print(f"  See {OUTPUT_DIR}/dataset_summary.txt for details")
    
    print("\n✓ Ready for training!")
    print(f"  Use this config with YOLO: {OUTPUT_DIR}/data.yaml")
    print("=" * 70)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nProcess interrupted by user.")
    except Exception as e:
        print(f"\n\nError: {e}")
        import traceback
        traceback.print_exc()